# Generated by Django 3.2.18 on 2023-03-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('SO', 'Супы'), ('SD', 'Гарниры'), ('MC', 'Главное блюдо'), ('DR', 'Напитки'), ('SN', 'Закуски'), ('SA', 'Салаты')], default='SO', max_length=2),
        ),
    ]
